'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { useRegisterStore } from "@/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Prototype",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const {
    cep,
    city,
    complement,
    confirmEmail,
    confirmPassword,
    cpf,
    email,
    fullName,
    number,
    password,
    phone,
    state,
    street
  } = useRegisterStore(state => state)

  return (
    <html lang="pt-br">
      <body className={`${inter.className} container py-20 px-4 flex flex-col items-center gap-5 mx-auto`}>
        {children}
        <pre>
          <code>
            {JSON.stringify({
              cep,
              city,
              complement,
              confirmEmail,
              confirmPassword,
              cpf,
              email,
              fullName,
              number,
              password,
              phone,
              state,
              street
            }, null, 2)}
          </code>
        </pre>
        <Toaster />
      </body>
    </html>
  );
}
